### ISSUE TITLE
Add a License

### ISSUE THREAD

**Issue by ZuseZ4** [rust-ml/oxide-enzyme#3]
We should agree on a License @bytesnake.
I would prefer MIT / Apache2, as it's the default for the rust side.
However, we should verify that this isn't conflicting with LLVM's / Enzyme's   Apache2-with-LLVM-exceptions licsense.

**Comment by bytesnake** [comment]
yes I'm fine with the MIT / Apache2 duo

**Comment by ZuseZ4** [comment]
Closed by #5
